[package]
name = "nodepy/nodepy-pm"
version = "0.1.0"
license = "MIT"
description = "The Node.py package manager"
repository = "https://github.com/nodepy/nodepy"
authors = [
  "Niklas Rosenstein <rosensteinniklas@gmail.com>"
]
main = "index"
bin = [
  "nppm${py} = index"
]
engines = [
  "nodepy >=0.1.0",
  "python >=2.7.0 || >=3.3.0"
]

[python_dependencies]
appdirs = ">=1.4.2"
click = ">=6.7"
distlib = ">=0.2.4"
hammock = ">=0.2.4"
jsonschema = ">=2.6.0"
requests = ">=2.13.0"
